# Service and ingress.
service:
  port: 443
  internalPort: 8443

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.allow-http: "false"
    # kubernetes.io/ingress.global-static-ip-name: pipecd

# Workloads.
gateway:
  replicasCount: 1
  imageTag: v1.10.0
  resources: {}

api:
  replicasCount: 1
  args:
    cacheAddress: ""
    useFakeResponse: false
    enableGRPCReflection: true
    insecureCookie: false
  resources: {}

web:
  replicasCount: 1
  resources: {}

cache:
  imageTag: "5.0.5-alpine3.9"
  password: ""
  resources: {}

operator:
  resources: {}

mongodb:
  imageTag: "4.2"

minio:
  imageTag: "RELEASE.2020-08-26T00-00-49Z"

# Control Plane Configurations.
config:
  # Specifies whether a ConfigMap for control plane configuration should be created
  create: true
  # The name of the ConfigMap to use when create is false.
  name: ""
  # The name of the configuration file.
  fileName: control-plane-config.yaml
  # Configuration data for control plane when create is false.
  data: |
    apiVersion: "pipecd.dev/v1beta1"
    kind: ControlPlane
    spec:

# Secret files that can be used in above configuration.
secret:
  # Specifies whether a Secret for storing sensitive data should be created.
  create: true
  # The name of the Secret should be mounted to container.
  name: "pipecd-secrets"
  mountPath: /etc/pipecd-secret
  signingKey:
    fileName: "signing-key"
    data: ""
  firestoreServiceAccount:
    fileName: "firestore-service-account"
    data: ""
  gcsServiceAccount:
    fileName: "gcs-service-account"
    data: ""
  minioAccessKey:
    fileName: "minio-access-key"
    data: ""
  minioSecretKey:
    fileName: "minio-secret-key"
    data: ""
  internalTLSKey:
    fileName: "internal-tls.key"
    data: ""
  internalTLSCert:
    fileName: "internal-tls.cert"
    data: ""


# Optional configuration for GKE.
backendConfig:
  enabled: false
  iap:
    enabled: false
    secretName: pipecd-iap

managedCertificate:
  enabled: false
  domains: []

cors:
  enabled: false
  allowOrigins:
    - "http://localhost:9090"

quickstart: false