# Service and ingress.
service:
  port: 8080
  internalPort:
  type: "NodePort"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.allow-http: "false"
    # kubernetes.io/ingress.global-static-ip-name: pipecd

# Workloads.
gateway:
  replicasCount: 1
  imageTag: v1.18.3
  resources: {}
  internalTLS:
    enabled: false

server:
  image:
    repository: gcr.io/pipecd/pipecd
  replicasCount: 1
  args:
    cacheAddress: ""
    enableGRPCReflection: false
    secureCookie: false
    logEncoding: humanize
    metrics: true
  resources: {}
  env: []

cache:
  imageTag: "5.0.5-alpine3.9"
  password: ""
  resources: {}

ops:
  image:
    repository: gcr.io/pipecd/pipecd
  args:
    logEncoding: humanize
  resources: {}

mysql:
  imageTag: "8.0.23"
  resources: {}

minio:
  imageTag: "RELEASE.2020-08-26T00-00-49Z"
  resources: {}

# Control Plane Configurations.
config:
  # Specifies whether a ConfigMap for control plane configuration should be created
  create: true
  # The name of the ConfigMap to use when create is false.
  name: ""
  # The name of the configuration file.
  fileName: control-plane-config.yaml
  # Configuration data for control plane when create is false.
  data: |
    apiVersion: "pipecd.dev/v1beta1"
    kind: ControlPlane
    spec:

# Secret files that can be used in above configuration.
secret:
  # Specifies whether a Secret for storing sensitive data should be created.
  create: true
  # The name of the Secret should be mounted to container.
  name: "pipecd-secrets"
  mountPath: /etc/pipecd-secret
  encryptionKey:
    fileName: "encryption-key"
    data: ""
  firestoreServiceAccount:
    fileName: "firestore-service-account"
    data: ""
  gcsServiceAccount:
    fileName: "gcs-service-account"
    data: ""
  minioAccessKey:
    fileName: "minio-access-key"
    data: ""
  minioSecretKey:
    fileName: "minio-secret-key"
    data: ""
  internalTLSKey:
    fileName: "internal-tls.key"
    data: ""
  internalTLSCert:
    fileName: "internal-tls.cert"
    data: ""


# Optional configuration for GKE.
backendConfig:
  enabled: false
  iap:
    enabled: false
    secretName: pipecd-iap

managedCertificate:
  enabled: false
  domains: []

cors:
  enabled: false
  allowOrigins:
    - "http://localhost:9090"

quickstart: false

monitoring:
  # If true, prometheus and grafana sub-charts will be installed
  enabled: false

# All directives inside this section will be directly sent to the prometheus chart.
# Head to the below link to see all available values.
# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
prometheus:
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: true
    service:
      hostPort: 9100
      servicePort: 9100
  kubeStateMetrics:
    enabled: true
  configmapReload:
    prometheus:
      enabled: true
      extraVolumeDirs:
        - /etc/rules
      extraConfigmapMounts:
        - name: rules
          mountPath: /etc/rules
          readOnly: true
          configMap: pipecd-prometheus-server-rules
    alertmanager:
      enabled: true
  alertmanager:
    enabled: true
    useClusterRole: true
  alertmanagerFiles:
    alertmanager.yml:
      # The root node of the routing tree.
      route: {}
      # A list of notification receivers.
      receivers: []
  server:
    # Must be fixed so that Grafana can find out statically.
    fullnameOverride: pipecd-prometheus-server
    extraConfigmapMounts:
      - name: rules
        mountPath: /etc/rules
        readOnly: true
        configMap: pipecd-prometheus-server-rules
  serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/rules/alerting_rules.yml

      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
                - localhost:9090

        - job_name: pipecd-gateway
          scrape_interval: 1m
          metrics_path: /stats/prometheus
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: pipecd
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
              action: keep
              regex: gateway
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: envoy-admin
          metric_relabel_configs:
            - source_labels: [__name__]
              target_label: method
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_bucket$
              replacement: $4
            - source_labels: [__name__]
              target_label: __name__
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_bucket$
              replacement: pipecd_gateway_requests_duration_bucket
            - source_labels: [__name__]
              target_label: method
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_sum$
              replacement: $4
            - source_labels: [__name__]
              target_label: __name__
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_sum$
              replacement: pipecd_gateway_requests_duration_sum
            - source_labels: [__name__]
              target_label: method
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_count$
              replacement: $4
            - source_labels: [__name__]
              target_label: __name__
              regex: envoy_cluster_grpc_(.+)_(.+)_(.+)_(.+)_upstream_rq_time_count$
              replacement: pipecd_gateway_requests_duration_count

        - job_name: pipecd-server
          scrape_interval: 1m
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: pipecd
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
              action: keep
              regex: server
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: admin

        - job_name: pipecd-ops
          scrape_interval: 1m
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: pipecd
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
              action: keep
              regex: ops
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: admin

        # Scrape config for API servers.
        - job_name: kubernetes-apiservers
          kubernetes_sd_configs:
            - role: endpoints
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              action: keep
              regex: default;kubernetes;https

        - job_name: kubernetes-nodes
          kubernetes_sd_configs:
            - role: node
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics

        - job_name: kubernetes-nodes-cadvisor
          kubernetes_sd_configs:
            - role: node
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
          metric_relabel_configs:
            - source_labels: [pod]
              target_label: service
              regex: (.+)-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)$
              replacement: $1

        # Scrape config for services that has "prometheus.io/scrape: true"
        - job_name: kubernetes-service-endpoints
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: kubernetes_name
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: kubernetes_node
          metric_relabel_configs:
            - source_labels: [pod]
              target_label: service
              regex: (.+)-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)$
              replacement: $1

        # Scrape config for pods that has "prometheus.io/scrape: true"
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              action: replace
              regex: (https?)
              target_label: __scheme__
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: kubernetes_pod_name
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: Pending|Succeeded|Failed
              action: drop

# All directives inside this section will be directly sent to the grafana chart.
# Head to the below link to see all available values.
# https://github.com/grafana/helm-charts/tree/main/charts/grafana
grafana:
  adminPassword: admin
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      # Label that the configmaps with dashboards are marked with
      label: grafana_dashboard
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://pipecd-prometheus-server
          access: proxy
          version: 1
