linters:
  disable-all: true
  enable:
    - prealloc
    - ineffassign
    - gosimple
    - staticcheck
    - gosec
    - gocritic
    - unparam
    - deadcode
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/pipe-cd/pipe
