{{- if .Values.backendConfig.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "pipecd.fullname" . }}
spec:
  iap:
    enabled: {{ .Values.backendConfig.iap.enabled }}
    oauthclientCredentials:
      secretName: {{ .Values.backendConfig.ipa.secretName }}
{{- end }}
