{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipecd.fullname" . }}
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |-
{{ tpl .Values.config.data . | indent 4 }}
{{- end }}

{{- if .Values.monitoring.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipecd.fullname" . }}-grafana-dashboards
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    grafana_dashboard: "1"
data:
  # TODO: Make dashboard for application metrics
{{ range $path, $_ :=  .Files.Glob  "grafana-dashboards/**.json" }}
  {{ trimPrefix "grafana-dashboards/" $path | nindent 2 }}: |-
    {{ $.Files.Get $path | nindent 4 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipecd-prometheus-server-rules
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
data:
{{ range $path, $_ :=  .Files.Glob  "prom-rules/**.yml" }}
  {{ trimPrefix "prom-rules/" $path | nindent 2 }}: |-
    {{ $.Files.Get $path | nindent 4 }}
{{ end }}
{{- end }}
