# Gateway workload by using Envoy proxy.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-gateway
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicasCount }}
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:{{ .Values.gateway.imageTag }}
          imagePullPolicy: IfNotPresent
          command:
          - envoy
          args:
            - -c
            - /etc/envoy/envoy-config.yaml
          ports:
          - name: ingress
            containerPort: 9090
            protocol: TCP
          - name: envoy-admin
            containerPort: 9095
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /server_info
              port: envoy-admin
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /server_info
              port: envoy-admin
          volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy
            readOnly: true
          - name: pipecd-secret
            mountPath: {{ .Values.secret.mountPath }}
            readOnly: true
{{- if .Values.gateway.resources }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
{{- end }}
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "pipecd.fullname" . }}-gateway-envoy-config
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}

---
# API workload.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-api
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicasCount }}
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "gcr.io/pipecd/api:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - server
{{- if not .Values.api.args.secureCookie }}
          - --insecure-cookie=true
{{- end }}
          - --cache-address={{ .Values.api.args.cacheAddress | default (printf "%s-cache:6379" (include "pipecd.fullname" .)) }}
          - --config-file=/etc/pipecd-config/{{ .Values.config.fileName }}
          - --use-fake-response={{ .Values.api.args.useFakeResponse }}
          - --enable-grpc-reflection={{ .Values.api.args.enableGRPCReflection }}
          - --encryption-key-file={{ .Values.secret.mountPath }}/{{ .Values.secret.encryptionKey.fileName }}
          ports:
            - name: piped-api
              containerPort: 9080
              protocol: TCP
            - name: web-api
              containerPort: 9081
              protocol: TCP
            - name: http
              containerPort: 9082
              protocol: TCP
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            - name: pipecd-config
              mountPath: /etc/pipecd-config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}
        - name: pipecd-config
          configMap:
            name: {{ include "pipecd.configMapName" . }}
{{- if .Values.api.resources }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
{{- end }}

---
# Web workload.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-web
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicasCount }}
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "gcr.io/pipecd/web:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - server
          ports:
            - name: web
              containerPort: 9082
              protocol: TCP
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
{{- if .Values.web.resources }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}

---
# Cache workload.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-cache
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: cache
          image: redis:{{ .Values.cache.imageTag }}
          imagePullPolicy: IfNotPresent
  {{- if .Values.cache.password }}
          args:
            - --requirepass
            - {{ .Values.cache.password | quote }}
  {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
{{- if .Values.cache.resources }}
          resources:
            {{- toYaml .Values.cache.resources | nindent 12 }}
{{- end }}

---
# Single ops pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-ops
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ops
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ops
    spec:
      containers:
        - name: ops
          image: "gcr.io/pipecd/ops:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - server
          - --config-file=/etc/pipecd-config/{{ .Values.config.fileName }}
          ports:
            - name: http
              containerPort: 9082
              protocol: TCP
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            - name: pipecd-config
              mountPath: /etc/pipecd-config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}
        - name: pipecd-config
          configMap:
            name: {{ include "pipecd.configMapName" . }}
{{- if .Values.ops.resources }}
          resources:
            {{- toYaml .Values.ops.resources | nindent 12 }}
{{- end }}

{{- if .Values.quickstart}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-mongodb
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:{{ .Values.mongodb.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-minio
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:{{ .Values.minio.imageTag }}
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "pipecd.secretName" . }}
              key: {{ .Values.secret.minioAccessKey.fileName }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "pipecd.secretName" . }}
              key: {{ .Values.secret.minioSecretKey.fileName }}
        ports:
          - name: minio
            containerPort: 9000
            protocol: TCP
{{- end }}
