{{- if .Values.managedCertificate.enabled -}}
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: {{ include "pipecd.fullname" . }}
spec:
  domains:
  {{- range .Values.managedCertificate.domains }}
  - {{ . }}
  {{- end }}
{{- end }}
