{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipecd.secretName" . }}
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.secret.signingKey.data }}
  {{ .Values.secret.signingKey.fileName }}: {{ .Values.secret.signingKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.firestoreServiceAccount.data }}
  {{ .Values.secret.firestoreServiceAccount.fileName }}: {{ .Values.secret.firestoreServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.gcsServiceAccount.data }}
  {{ .Values.secret.gcsServiceAccount.fileName }}: {{ .Values.secret.gcsServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.minioAccessKey.data }}
  {{ .Values.secret.minioAccessKey.fileName }}: {{ .Values.secret.minioAccessKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.minioSecretKey.data }}
  {{ .Values.secret.minioSecretKey.fileName }}: {{ .Values.secret.minioSecretKey.data | b64enc | quote }}
{{- end }}
{{- end }}
