{
 "title": "Pod",
 "description": "For white-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time of $service pods",
   "type": "stat",
   "description": "When the latest pod got started",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kubernetes_node) (kube_pod_start_time{service=\"$service\"} * 1000)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Available Number of $service Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{deployment=\"$service\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{deployment=\"$service\"})",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Restart number of $service Pod [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(kube_pod_container_status_restarts_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage of $service Pod [rate-5m]",
   "type": "graph",
   "description": "CPU usage per Pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  rate(container_cpu_usage_seconds_total{\n    service=\"$service\"\n  }[5m]) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage of $service Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  container_memory_usage_bytes{\n    service=\"$service\"\n  } / (1024 * 1024)\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors of $service",
   "type": "graph",
   "description": "Number of open file descriptors for the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (container_file_descriptors{service=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage of $service",
   "type": "graph",
   "description": "Number of bytes that are consumed by the container on this filesystem.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (container_fs_usage_bytes{service=\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}