{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Last Config Reload ",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "stat",
   "description": "Timestamp of the last successful configuration reload.",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds * 1000"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"pipecd-prometheus-server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Samples in the head",
   "type": "stat",
   "description": "Total number of series in the head block.",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Ingested Samples/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])"
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "5xx Error Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(prometheus_http_requests_total{code=~\"5.*\"}[5m]))\n/\nsum by (handler) (rate(prometheus_http_requests_total[5m]))\n* 100",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "99th Quantile of HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/graph\"}[5m]))\n)",
     "legendFormat": "graph"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/api/v1/query\"}[5m]))\n)",
     "legendFormat": "query"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/api/v1/query_range\"}[5m]))\n)",
     "legendFormat": "query_range"
    }
   ]
  },
  { "title": "Resource Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[5m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Heap Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  }
 ]
}