apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piped.fullname" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "piped.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "piped.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ include "piped.fullname" . }}
      containers:
        - name: piped
          image: "gcr.io/pipecd/piped:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - piped
          - --config-file=/etc/piped-config/{{ .Values.config.fileName }}
          - --metrics={{ .Values.args.metrics }}
          - --control-plane-address={{ .Values.args.address }}
          - --use-fake-api-client={{ .Values.args.useFakeAPI }}
          - --enable-default-kubernetes-cloud-provider={{ .Values.args.enableDefaultKubernetesCloudProvider }}
          - --insecure={{ .Values.args.insecure }}
          ports:
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: piped-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            - name: piped-config
              mountPath: /etc/piped-config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: piped-secret
          secret:
            secretName: {{ include "piped.secretName" . }}
            defaultMode: 0400
        - name: piped-config
          configMap:
            name: {{ include "piped.configMapName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
