{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piped.secretName" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.pipedKey.fileName }}: {{ required "piped key is required" .Values.secret.pipedKey.data | b64enc | quote }}
{{- if .Values.secret.sshKey.data }}
  {{ .Values.secret.sshKey.fileName }}: {{ .Values.secret.sshKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretSealingKey.publicKey.data }}
  {{ .Values.secret.sealedSecretSealingKey.publicKey.fileName }}: {{ .Values.secret.sealedSecretSealingKey.publicKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretSealingKey.privateKey.data }}
  {{ .Values.secret.sealedSecretSealingKey.privateKey.fileName }}: {{ .Values.secret.sealedSecretSealingKey.privateKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.data }}
  {{ .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.fileName }}: {{ .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.data }}
  {{ .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.fileName }}: {{ .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.awsCredentials.data }}
  {{ .Values.secret.awsCredentials.fileName }}: {{ .Values.secret.awsCredentials.data | b64enc | quote }}
{{- end }}
{{- end }}
