{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piped.configMapName" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.pipedKey.fileName }}: {{ .Values.secret.pipedKey.data | b64enc | quote }}
  {{ .Values.secret.sshKey.fileName }}: {{ .Values.secret.sshKey.data | b64enc | quote }}
{{- end }}
