{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "piped.fullname" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: admin
      port: {{ .Values.service.port }}
      targetPort: admin
  selector:
    {{- include "piped.selectorLabels" . | nindent 4 }}
{{- end }}