apiVersion: "pipecd.dev/v1beta1"
kind: ControlPlane
spec:
  datastore:
    type: MONGODB
    config:
      url: mongodb://pipecd-datastore:27017/test
      database: test
  filestore:
    type: MINIO
    config:
      endpoint:
      bucket:
      accessKeyFile:
      secretKeyFile:
  project:
    - name: example
      staticAdmin:
        username: hello-pipecd
        passwordHash: "$2a$10$ye96mUqUqTnjUqgwQJbJzel/LJibRhUnmzyypACkvrTSnQpVFZ7qK" # bcrypt value of "hello-pipecd"
