{{- if .Values.backendConfig.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: internal-site
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: site-iap
{{- end }}
