{{- if .Values.managedCertificate.enabled -}}
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: site
spec:
  domains:
  {{- range .Values.ingress.domains }}
  - {{ . }}
  {{- end }}
{{- end }}
