apiVersion: v1
kind: Service
metadata:
  name: {{ include "site.fullname" . }}
  labels:
    {{- include "site.labels" . | nindent 4 }}
  {{- if .Values.backendConfig.enabled }}
  annotations:
  {{- nindent 4 (toYaml .Values.backendConfig.annotation) }}
  {{- end }}
spec:
  {{- if .Values.ingress.enabled }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "site.selectorLabels" . | nindent 4 }}
