{
 "title": "Go",
 "description": "For white-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Go version of $service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (go_info{job=\"$service\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "OS Thread of $service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Stats of $service",
   "type": "graph",
   "description": "Heap metrics reported by Go",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (go_memstats_heap_alloc_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "alloc"
    },
    {
     "expr": "sum by (job) (go_memstats_heap_inuse_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "inuse"
    },
    {
     "expr": "sum by (job) (go_memstats_heap_idle_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "GC Duration Average of $service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"$service\"}[5m])\n/\nrate(go_gc_duration_seconds_count{job=\"$service\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines of $service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}